controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\HomeController::index

app_register:
    path: '/api/register'
    controller: 'App\Controller\UserController::register'
    methods: [ 'POST' ]

app_login:
    path: '/api/login'
    controller: 'App\Controller\SecurityController::login'
    methods: [ 'POST' ]